config/routes.rb
Cms::Application.routes.draw do
  get "admin/dashboard"
  root 'welcome#index'
  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  get "welcome/photos"
  get "welcome/links"
  get "welcome/blog"

  resources :pages
  resources :welcome
  resources :products
  get 'admin' => 'admin#dashboard', as: :admin

  

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :photo
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: "osvaldo", password: "pravo"
  def dashboard
    @pages = Page.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: "osvaldo", password: "pravo"
  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to pages_path
    else
      render 'new'
    end
  end
  def destroy
    @page = Page.find(params[:id])
    @page.delete
    redirect_to pages_path
  end

  def show
  end
  private
  def set_page
    @page = Page.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:name, :title, :content)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  http_basic_authenticate_with name: "osvaldo", password: "pravo"
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.delete
    redirect_to products_path
  end

  def show
  end
  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price,:photo)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def about
  end
  def contact
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dashboard.html.erb
<h1>Admin Dashboard</h1>
<h2>Todo</h2>
<%= link_to "Manage Pages", pages_path, id: "manage_pages"  %><br>
<%= link_to "Manage Products", products_path, id: "manage_products"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cms</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
  <div id="wrapper-bgbtm">
    <div id="header">
      <div id="logo">
        <h1><a href="#">Wood Working </a></h1>
        <p>template design by <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a></p>
      </div>
    </div>
    <!-- end #header -->
    <div id="menu">
      <ul>
        <li class="current_page_item"><%= link_to "Home", root_path %></li>
        <li><%= link_to "Blog", welcome_blog_path %></li>
        <li><%= link_to "Photos", welcome_photos_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Links", welcome_links_path %></li>
        <li><%= link_to "Contact", welcome_contact_path %></li>
      </ul>
    </div>
  </div>
 </div>

<%= yield %>
<div id="sidebar">
  <div id="search">
    <h2>Search</h2>
    <form method="get" action="">
      <fieldset>
        <input type="text" name="s" id="search-text" size="15" value="enter keywords here..." />
        <input type="submit" id="search-submit" value="GO" />
      </fieldset>
    </form>
  </div>
  <ul>
    <li>
      <h2>Aliquam tempus</h2>
      <p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper consectetuer hendrerit.</p>
    </li>
    <li>
      <h2>Categories</h2>
      <ul>
        <li><a href="#">Aliquam libero</a></li>
        <li><a href="#">Consectetuer adipiscing elit</a></li>
        <li><a href="#">Metus aliquam pellentesque</a></li>
        <li><a href="#">Suspendisse iaculis mauris</a></li>
        <li><a href="#">Urnanet non molestie semper</a></li>
        <li><a href="#">Proin gravida orci porttitor</a></li>
      </ul>
    </li>
    <li>
      <h2>Blogroll</h2>
      <ul>
        <li><a href="#">Aliquam libero</a></li>
        <li><a href="#">Consectetuer adipiscing elit</a></li>
        <li><a href="#">Metus aliquam pellentesque</a></li>
        <li><a href="#">Suspendisse iaculis mauris</a></li>
        <li><a href="#">Urnanet non molestie semper</a></li>
        <li><a href="#">Proin gravida orci porttitor</a></li>
      </ul>
    </li>
    <li>
      <h2>Archives</h2>
      <ul>
        <li><a href="#">Aliquam libero</a></li>
        <li><a href="#">Consectetuer adipiscing elit</a></li>
        <li><a href="#">Metus aliquam pellentesque</a></li>
        <li><a href="#">Suspendisse iaculis mauris</a></li>
        <li><a href="#">Urnanet non molestie semper</a></li>
        <li><a href="#">Proin gravida orci porttitor</a></li>
      </ul>
    </li>
  </ul>
</div>
</body>
</html>

app/views/pages/index.html.erb
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @pages.each do |page| %>
      <tr>
        <td><%= page.name %></td>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
            <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<br>
    <%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>Create new page</h1>

<%= form_for @page do |form| %>
    <p>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :content %>
      <%= form.text_field :content %>
    </p>
    <%= form.submit "Save" %>
<% end %>

app/views/pages/show.html.erb
<h1>Show pages</h1>

<%= @page.name %>

app/views/products/index.html.erb
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= image_tag product.photo.url %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>Create new product</h1>

<%= form_for @product do |form| %>
    <p>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :description %>
      <%= form.text_field :description %>
    </p>
    <p>
      <%= form.file_field :photo %>
    </p>
    <p>
      <%= form.label :price %>
      <%= form.text_field :price %>
    </p>
    <%= form.submit "Save" %>
<% end %>

app/views/products/show.html.erb
<h1>Show products</h1>


app/views/welcome/about.html.erb
<h1>About Us</h1>
<p >
The Hispanic Chamber of Commerce of Wisconsin was incorporated in 1972 as a non-profit business organization. The HCCW creates, expands and diversifies small and Hispanic-owned businesses in Wisconsin with a strong focus in the Milwaukee Metro area. The HCCW provides educational and technical resources, fosters economic exchange between the business and corporate sectors, and promotes a network for political issues, community affairs and opportunities for the Hispanic population and community at large.
</p>

app/views/welcome/blog.html.erb
<h1>Blog</h1>

app/views/welcome/contact.html.erb
<h2>Contact Us</h2>
<p>
HCCW Phone # (414) 643-6963
HCCW Fax# (414) 643-6994

Questions? Email us at hccwtoday@hccw.org

Bid information: bids@hccw.org

Chairman and CEO ~ Jorge Franco

(414) 643-6963 X.101 – gfranco@infc.net

Erica Steele ~ Director of Latino Empowerment

(414) 643-6963 X. 104 – erica@hccw.org

Natalia Bonilla ~ Associate Director of Workforce Development

(414) 643-6963 X. 1000 – nbonilla@hccw.org

Nathan Jones ~ Associate Director of Latino Empowerment

(414) 643-6963 X. 104 – neizan.jones@gmail.com

Israel Cruz ~ Facility Manager

(414) 643-6963 -  icruz@wi.rr.com
</p>

app/views/welcome/index.html.erb
<div id="page">
  <div id="page-bgtop">
    <div id="page-bgbtm">
      <div id="content">
        <div class="post">
          <h2 class="title"><a href="#">Welcome to my website</a></h2>
          <p class="meta">Posted by <a href="#">Someone</a> on July 10, 2011
            &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
          <div class="entry">
            <p><%= image_tag "img02.jpg",  width:"143", height:"143", alt:"", class:"alignleft border" %>This is <strong>Wood Working </strong>, a free, fully standards-compliant CSS template designed by <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a>.  The picture in this template is from <a href="#">PDPhoto.org</a>. This free template is released under a <a href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attributions</a> license, so you’re pretty much free to do whatever you want with it (even use it commercially) provided you keep the links in the footer intact. Aside from that, have fun with it :)</p>
            <p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in felis. Donec ut ante. In id eros. Suspendisse lacus turpis at sem. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. </p>
          </div>
        </div>

      </div>

app/views/welcome/links.html.erb
<h1>Links</h1>

app/views/welcome/photos.html.erb
<h1>This Photos </h1>

<p>
  <div>
  <%= image_tag "img02.jpg", style: "border; 39px solid red;", width:"143", height:"143", alt:"", class:"alignleft border" %>
</div>
<div>
  <%= image_tag "img03.jpg", style: "border; 19px solid red;",  width:"143", height:"143", alt:"", class:"alignleft border" %>
</div>
</p>